title: nfstream
email: aouinizied@gmail.com
description: nfstream is a Python package providing fast, flexible, and expressive data structures designed to make working with online or offline network data both easy and intuitive.
image: /resources/preview.png
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nfstream.org"
twitter_username: aouinizied
github_username:  aouinizied
logo_source: /resources/logo_white.png
logo_sah: /resources/logo_sah.png
logo_tuke: /resources/logo_tuke.png
logo_ntop: /resources/logo_ntop.png
logo_width: 180

# Build settings
markdown: kramdown
remote_theme: aouinizied/just-the-docs
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-sitemap

# Enable or disable the site search
search_enabled: true

# Enable or disable top navigation panel
top_navigation_enabled: true

# nfstream specific variables
is_new_release: true

# Google Analytics Tracking Id
ga_tracking: UA-162172644-1

include:
  - _*_8h.html
  - _*_8h_source.html
  - _*_8h.js

exclude:
  - README.md

